### ISSUE TITLE
Feedback on multi-language and icon issues

### ISSUE THREAD

**Issue by WuChenDi** [zolplay-cn/website#11]
Great-looking project, but I noticed a few small issues when I opened it:

- Icons are not displaying correctly, but I didn't see any failed requests in the network.
- The language switcher doesn't work, even though I can see that the URL has changed from https://zolplay.com/ to https://cn.zolplay.com/en.

`user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`

![image](https://github.com/zolplay-cn/website/assets/31385662/19dd144e-1ae8-417e-901b-611cb734e4b5)

**Comment by CaliCastle** [comment]
Thank you for your feedback @WuChenDi 

> Icons are not displaying correctly, but I didn't see any failed requests in the network.
Those are actually emojis, for some reason it didn't work in your browser? Are you on Linux by chance?

> The language switcher doesn't work, even though I can see that the URL has changed from https://zolplay.com/ to https://cn.zolplay.com/en.

I've updated some config, languages should work properly now, sorry about that!

**Comment by WuChenDi** [comment]
Thank you for your reply, it's great! @CaliCastle 

> Those are actually emojis, for some reason it didn't work in your browser? Are you on Linux by chance?

No, my working environment usually involves switching between Windows and Linux.

**Comment by CaliCastle** [comment]
The font stack I'm using should cover emojis, not sure why it's not rendering on your machine 🤔

**Comment by WuChenDi** [comment]
It may only happen on my end, in rare cases. Let's put it aside for now, as it doesn't affect the usage.
