### ISSUE TITLE
NEXT_PUBLIC_OG_URL is a typo?

### ISSUE THREAD

**Issue by liwn9527** [zolplay-cn/website#8]
In the given code snippet at, https://github.com/zolplay-cn/website/blob/12c9f7fa797c87b11ea3eaac0821feda01103d61/lib/helper.ts#L7
a variable named NEXT_PUBLIC_OG_URL is used. However, in the .env.example file, there is a variable named NEXT_PUBLIC_OG_URL_PREFIX. https://github.com/zolplay-cn/website/blob/12c9f7fa797c87b11ea3eaac0821feda01103d61/.env.example#L24 Is this a typo or intentional?

**Comment by CaliCastle** [comment]
Oh good catch! I've only updated the `.env` file locally and forgot to sync it back to the `.env.example` file afterwards.

I'll update it, thanks for spotting it!
